import { strToU8, zipSync } from 'fflate'
import { SKILL_CONTENT } from './skillsContent'

function buildSetupGuide(owner: string, repo: string, skills: string[]): string {
  return `# MARK Intelligence — Setup Guide
Generated for: ${owner}/${repo}

## Quick Start
1. Copy CLAUDE.md to your project root
2. Add the skill files to .claude/skills/
3. Run: claude code

## Selected Skills (${skills.length}/59)
${skills.map(s => `- ${s}`).join('\n')}

## What this gives Claude Code
- Full understanding of your tech stack
- Coding conventions and patterns from this codebase
- Ready-to-use skill files for your specific setup

Generated by MARK Intelligence — markintel.xyz
`
}

export async function buildZip(
  markFile: string,
  skills: string[],
  owner: string,
  repo: string
): Promise<string> {
  const files: Record<string, Uint8Array> = {
    'CLAUDE.md': strToU8(markFile),
    'SETUP_GUIDE.md': strToU8(buildSetupGuide(owner, repo, skills)),
  }

  for (const skill of skills) {
    const content = SKILL_CONTENT[skill]
    if (content) {
      files[`.claude/skills/${skill}.md`] = strToU8(content)
    }
  }

  const zipped = zipSync(files, { level: 6 })
  return Buffer.from(zipped).toString('base64')
}
