export interface TerminalLine {
  c: string
  t: string
}

export interface SkillEntry {
  name: string
  pct: number
}

export interface EpLine {
  d: number
  c: string
  t: string
}

export interface EpChip {
  d: number
  t: string
  bg: string
  bd: string
  fg: string
}

export interface MfLinePart {
  c: string
  t: string
  fw?: string
}

export interface MfLine {
  parts: MfLinePart[]
}

export interface IdeaItem {
  name: string
  tk: string
  desc: string
  est: string
}

export const TERM_LINES: TerminalLine[] = [
  { c: '#7DAEEA', t: '→ reading manifest files...' },
  { c: '#7DAEEA', t: '→ stack: Next.js 14 · TypeScript · React 18' },
  { c: '#7DAEEA', t: '→ core capability: web framework / SSR' },
  { c: '#E8C56A', t: '→ matching 59 skill patterns...' },
  { c: '#6DBE8A', t: '→ 8 skills matched ✓' },
  { c: '#6DBE8A', t: '→ CLAUDE.md generated ✓' },
  { c: '#6DBE8A', t: '→ build ideas generated ✓' },
]

export const TAGS = [
  'next-js-app-router', 'typescript-strict', 'react-patterns',
  'web-performance', 'tailwind', 'prisma-orm', 'zod-validation', '+1 more',
]

export const SKILLS: SkillEntry[] = [
  { name: 'architecture-depth', pct: 92 },
  { name: 'skill-match', pct: 72 },
  { name: 'type-coverage', pct: 88 },
]

export const TAB_DUR = [7000, 6000, 5000]

export const EP_LINES: EpLine[] = [
  { d: 900, c: '#7DAEEA', t: '→ C++ · Python · CMake' },
  { d: 1700, c: '#7DAEEA', t: '→ speech inference' },
  { d: 2600, c: '#6DBE8A', t: '→ 6 skills matched ✓' },
]

export const EP_CHIPS: EpChip[] = [
  { d: 800, t: 'C++', bg: 'rgba(247,246,243,.9)', bd: 'rgba(229,227,220,.9)', fg: '#0F0F0E' },
  { d: 1500, t: 'Python', bg: 'rgba(247,246,243,.9)', bd: 'rgba(229,227,220,.9)', fg: '#0F0F0E' },
  { d: 2200, t: 'CMake', bg: 'rgba(247,246,243,.9)', bd: 'rgba(229,227,220,.9)', fg: '#0F0F0E' },
  { d: 3000, t: '6 skills', bg: 'rgba(235,242,255,.9)', bd: 'rgba(195,215,247,.9)', fg: '#1A47A8' },
]

const NBSP = '\u00A0'

export const MF_LINES: MfLine[] = [
  { parts: [{ c: '#3a3a38', t: '# Generated by MARK Intelligence' }] },
  { parts: [{ c: '#ffffff', t: '# CLAUDE.md — whisper.cpp', fw: '600' }] },
  { parts: [{ c: '#3a3a38', t: NBSP }] },
  { parts: [{ c: '#E8C56A', t: '## Project Overview' }] },
  { parts: [{ c: '#E8E6E0', t: 'C++ port of OpenAI Whisper.' }] },
  { parts: [{ c: '#E8E6E0', t: 'Core: speech-to-text inference.' }] },
  { parts: [{ c: '#3a3a38', t: NBSP }] },
  { parts: [{ c: '#E8C56A', t: '## Tech Stack' }] },
  { parts: [{ c: '#7DAEEA', t: 'Language:' }, { c: '#E8E6E0', t: 'C++17, Python' }] },
  { parts: [{ c: '#7DAEEA', t: 'Build:' }, { c: '#E8E6E0', t: 'CMake 3.17+' }] },
  { parts: [{ c: '#7DAEEA', t: 'Backends:' }, { c: '#E8E6E0', t: 'Metal · CUDA · WASM' }] },
  { parts: [{ c: '#3a3a38', t: NBSP }] },
  { parts: [{ c: '#E8C56A', t: '## Selected Skills (6/59)' }] },
  { parts: [{ c: '#7DAEEA', t: 'cpp-inference, audio-processing,' }] },
  { parts: [{ c: '#7DAEEA', t: 'cross-platform-build, wasm-deploy' }] },
]

export const IDEAS: IdeaItem[] = [
  {
    name: 'SpacesTranscribe.xyz',
    tk: '$SPACES',
    desc: 'Transcribe any Twitter Space in 60s using whisper.cpp as the engine',
    est: '~4 days',
  },
  {
    name: 'VoiceMark.xyz',
    tk: '$VOICE',
    desc: 'Voice memo → CLAUDE.md context. Every Claude Code user is potential holder',
    est: '~3 days',
  },
  {
    name: 'PodcastBrief.xyz',
    tk: '$BRIEF',
    desc: 'Auto-clip alpha drops from crypto podcasts. Feed wallets, not just degens',
    est: '~5 days',
  },
]

export interface MascotBadge {
  label: string
  bg: string
  fg: string
  bd: string
  style: Record<string, string>
  delay: string
}

export const MASCOT_BADGES: MascotBadge[] = [
  { label: 'scanning repo…', bg: '#EBF2FF', fg: '#1A47A8', bd: '#C3D7F7', style: { top: '6%', left: '-4%' }, delay: '0s' },
  { label: '8 skills matched ✓', bg: '#E9F5E9', fg: '#1B6B28', bd: '#B6DEB9', style: { top: '30%', right: '-8%' }, delay: '.8s' },
  { label: '$MARK', bg: '#F7F6F3', fg: '#888785', bd: '#E5E3DC', style: { bottom: '12%', left: '-2%' }, delay: '1.6s' },
]

export const TICKER_ITEMS = [
  { repo: 'vercel/next.js', ticker: '$DEPLOY' },
  { repo: 'ggerganov/whisper.cpp', ticker: '$SPACES' },
  { repo: 'supabase/supabase', ticker: '$BASE' },
  { repo: 'microsoft/vscode', ticker: '$EXT' },
  { repo: 'langchain-ai/langchain', ticker: '$CHAIN' },
]

export const SKILL_CATS = [
  'Code Quality',
  'Git',
  'Testing',
  'React / Frontend',
  'TypeScript',
  'Python',
  'Backend / API',
  'DevOps',
  'Architecture',
  'AI / LLM',
]

export type SkillLevel = keyof typeof LVL_STYLE

export const LVL_STYLE = {
  beginner: { fg: '#1B6B28', bg: '#E9F5E9', bd: '#B6DEB9' },
  intermediate: { fg: '#8a6d1a', bg: '#FBF4DF', bd: '#E8D9A8' },
  advanced: { fg: '#7a2f2f', bg: '#F9E9E9', bd: '#E5C3C3' },
} as const

export type SkillDefinition = [string, string, string, string, string[]]

export const SKILL_DB: SkillDefinition[] = [
  ['Code Quality', 'beginner', 'Clean Code Principles', 'Enforce readable, maintainable code with naming conventions, function size limits, and cognitive complexity guidance.', ['universal']],
  ['Code Quality', 'beginner', 'Code Review Checklist', 'Structured checklist covering correctness, security, performance, and readability.', ['universal']],
  ['Code Quality', 'intermediate', 'Error Handling Patterns', 'Consistent error handling strategies with proper logging and user-facing messages.', ['universal']],
  ['Code Quality', 'beginner', 'Naming Conventions', 'Project-wide naming rules for files, functions, variables, constants, and types.', ['universal']],
  ['Code Quality', 'intermediate', 'Refactoring Strategies', 'Safe, incremental refactoring patterns with clear criteria for when to refactor vs rewrite.', ['universal']],
  ['Code Quality', 'intermediate', 'SOLID Principles', 'Applied SOLID with concrete examples tailored to your language and architecture.', ['oop', 'typescript', 'python']],
  ['Code Quality', 'beginner', 'DRY & YAGNI', "Don't Repeat Yourself and You Aren't Gonna Need It — preventing over-engineering.", ['universal']],
  ['Code Quality', 'beginner', 'Code Documentation', 'JSDoc/docstring standards, inline comment rules, and README structure.', ['universal']],
  ['Git', 'beginner', 'Conventional Commits', 'Enforce conventional commit format enabling automated changelogs and semantic versioning.', ['universal']],
  ['Git', 'beginner', 'Branch Naming Strategy', 'Consistent branch naming patterns that integrate cleanly with issue trackers and CI/CD.', ['universal']],
  ['Git', 'beginner', 'Pull Request Best Practices', 'PR size limits, description templates, review etiquette, and merge strategies.', ['universal']],
  ['Git', 'beginner', 'Semantic Versioning', 'SemVer rules and communicating breaking changes clearly.', ['universal']],
  ['Git', 'intermediate', 'Trunk-Based Development', 'Trunk-based development with feature flags and short-lived branches.', ['universal']],
  ['Testing', 'beginner', 'Unit Testing Patterns', 'Arrange-Act-Assert, test naming, isolation principles, and coverage targets.', ['universal']],
  ['Testing', 'intermediate', 'Integration Testing', 'Testing service interactions, database operations, and API contracts.', ['universal']],
  ['Testing', 'intermediate', 'E2E Testing (Playwright)', 'End-to-end testing with Playwright: selectors, wait strategies, CI configuration.', ['playwright', 'nextjs', 'frontend']],
  ['Testing', 'intermediate', 'Test-Driven Development', 'Red-Green-Refactor cycle and how to integrate AI into the TDD workflow.', ['universal']],
  ['Testing', 'intermediate', 'Mocking & Stubbing', 'When to mock vs. use real implementations, and avoiding over-mocking.', ['universal']],
  ['Testing', 'beginner', 'Test Coverage Goals', "Meaningful coverage targets by code type and what coverage doesn't tell you.", ['universal']],
  ['Testing', 'beginner', 'Snapshot Testing', 'When snapshots help vs. hurt for UI components.', ['react', 'frontend']],
  ['React / Frontend', 'intermediate', 'React Component Patterns', 'Composition patterns, compound components, and when to use each approach.', ['react', 'nextjs', 'typescript']],
  ['React / Frontend', 'intermediate', 'State Management Strategy', 'Decision tree for local state vs. Zustand vs. TanStack Query.', ['react', 'nextjs']],
  ['React / Frontend', 'intermediate', 'Next.js App Router', 'App Router patterns: server/client components, layouts, route handlers, metadata API.', ['nextjs', 'react']],
  ['React / Frontend', 'beginner', 'Tailwind Design System', 'Tailwind config conventions, custom tokens, and component class patterns.', ['tailwind', 'react', 'nextjs']],
  ['React / Frontend', 'intermediate', 'Accessibility (a11y)', 'WCAG 2.1 AA compliance, semantic HTML, ARIA usage, and keyboard navigation.', ['frontend', 'react']],
  ['React / Frontend', 'advanced', 'Web Performance', 'Core Web Vitals targets, image optimisation, bundle analysis, lazy loading.', ['nextjs', 'react', 'frontend']],
  ['React / Frontend', 'intermediate', 'CSS Architecture', 'CSS Modules vs. Tailwind vs. CSS-in-JS decision guide and global style management.', ['frontend']],
  ['React / Frontend', 'intermediate', 'Component Library Setup', 'shadcn/ui integration, component variants with cva(), and Storybook docs.', ['react', 'nextjs', 'tailwind']],
  ['TypeScript', 'intermediate', 'TypeScript Strict Mode', 'Strict TypeScript config, rules to enforce, and common strict mode pitfalls.', ['typescript']],
  ['TypeScript', 'advanced', 'Type Design Patterns', 'Discriminated unions, branded types, utility types that prevent bugs at compile time.', ['typescript']],
  ['TypeScript', 'advanced', 'Generics Best Practices', 'When to use generics, constraints, inference, and avoiding over-generic code.', ['typescript']],
  ['TypeScript', 'intermediate', 'Zod Schema Validation', 'Zod schema patterns for API inputs, form validation, and env variable parsing.', ['typescript', 'nextjs']],
  ['Python', 'beginner', 'Python Style Guide', 'PEP 8+ rules via Ruff, Google-style docstrings, consistent project structure.', ['python']],
  ['Python', 'intermediate', 'Python Type Hints', 'Full type annotation coverage with mypy strict mode.', ['python']],
  ['Python', 'intermediate', 'Async/Await Patterns', 'asyncio patterns, FastAPI async conventions, and how to test async code.', ['python', 'fastapi']],
  ['Python', 'intermediate', 'CLI with Typer', 'Production-grade CLIs with Typer: commands, options, Rich output.', ['python', 'cli']],
  ['Python', 'beginner', 'Dependency Management (uv)', 'Modern Python dependency management with uv: lockfiles, virtual envs.', ['python']],
  ['Backend / API', 'intermediate', 'REST API Design', 'Resource naming, HTTP methods, status codes, pagination, and versioning.', ['api', 'backend']],
  ['Backend / API', 'advanced', 'GraphQL Patterns', 'Schema design, DataLoader for N+1, subscriptions.', ['graphql', 'api']],
  ['Backend / API', 'advanced', 'Auth & Authorization', 'JWT patterns, session management, RBAC, and authentication pitfalls.', ['api', 'security', 'backend']],
  ['Backend / API', 'intermediate', 'API Rate Limiting', 'Rate limiting strategies, response headers, user-friendly errors.', ['api', 'backend']],
  ['Backend / API', 'intermediate', 'Database Query Patterns', 'Prisma/SQLAlchemy conventions, N+1 prevention, migrations, transactions.', ['database', 'backend']],
  ['Backend / API', 'beginner', 'API Error Standards', 'Consistent error response structure and machine-readable codes.', ['api', 'backend']],
  ['Backend / API', 'intermediate', 'Webhook Handling', 'Receiving webhooks securely: signature verification, idempotency.', ['api', 'backend']],
  ['DevOps', 'intermediate', 'Docker Best Practices', 'Multi-stage builds, image size optimisation, security hardening.', ['docker', 'devops']],
  ['DevOps', 'intermediate', 'CI/CD with GitHub Actions', 'Workflows for lint, test, build, deploy with caching and matrix strategies.', ['github-actions', 'devops']],
  ['DevOps', 'beginner', 'Environment Management', '.env conventions, environment configs, and secret rotation.', ['devops']],
  ['DevOps', 'intermediate', 'Logging & Observability', 'Structured JSON logging with pino/structlog, log levels, OpenTelemetry.', ['devops', 'backend']],
  ['DevOps', 'advanced', 'Secrets Management', 'Vault, AWS Secrets Manager, GitHub OIDC for zero-trust secret handling.', ['security', 'devops']],
  ['Architecture', 'beginner', 'Project Structure', 'Opinionated folder structure for different project types.', ['universal']],
  ['Architecture', 'advanced', 'Monorepo Setup (Turborepo)', 'Turborepo configuration, workspace structure, shared packages.', ['monorepo', 'turborepo']],
  ['Architecture', 'advanced', 'Caching Strategies', 'In-memory, Redis, CDN, and HTTP caching with clean invalidation.', ['backend', 'performance']],
  ['Architecture', 'intermediate', 'Security Checklist', 'OWASP Top 10 coverage, dependency auditing, security review.', ['security', 'universal']],
  ['AI / LLM', 'intermediate', 'Prompt Engineering', 'System prompts, few-shot examples, chain-of-thought, and output formatting.', ['ai', 'llm']],
  ['AI / LLM', 'intermediate', 'LLM Integration Patterns', 'Anthropic SDK patterns, streaming, error handling, retry logic, cost management.', ['ai', 'anthropic', 'typescript']],
  ['AI / LLM', 'advanced', 'RAG Architecture', 'Retrieval-Augmented Generation: chunking, embedding, retrieval, re-ranking.', ['ai', 'llm', 'vector-db']],
  ['AI / LLM', 'advanced', 'Agent Design Patterns', 'ReAct pattern, tool design, agent memory architecture, multi-agent orchestration.', ['ai', 'agents', 'llm']],
  ['AI / LLM', 'advanced', 'MCP Server Integration', 'Building and integrating MCP servers with Claude Code.', ['mcp', 'claude-code', 'ai']],
  ['AI / LLM', 'beginner', 'Karpathy Coding Principles', "Andrej Karpathy's core coding philosophy adapted for Claude Code workflows.", ['universal', 'claude-code']],
]
