export interface TerminalLine {
  c: string
  t: string
}

export interface SkillEntry {
  name: string
  pct: number
}

export interface EpLine {
  d: number
  c: string
  t: string
}

export interface EpChip {
  d: number
  t: string
  bg: string
  bd: string
  fg: string
}

export interface MfLinePart {
  c: string
  t: string
  fw?: string
}

export interface MfLine {
  parts: MfLinePart[]
}

export interface IdeaItem {
  name: string
  tk: string
  desc: string
  est: string
}

export const TERM_LINES: TerminalLine[] = [
  { c: '#7DAEEA', t: '→ reading manifest files...' },
  { c: '#7DAEEA', t: '→ stack: Next.js 14 · TypeScript · React 18' },
  { c: '#7DAEEA', t: '→ core capability: web framework / SSR' },
  { c: '#E8C56A', t: '→ matching 59 skill patterns...' },
  { c: '#6DBE8A', t: '→ 8 skills matched ✓' },
  { c: '#6DBE8A', t: '→ CLAUDE.md generated ✓' },
  { c: '#6DBE8A', t: '→ build ideas generated ✓' },
]

export const TAGS = [
  'next-js-app-router', 'typescript-strict', 'react-patterns',
  'web-performance', 'tailwind', 'prisma-orm', 'zod-validation', '+1 more',
]

export const SKILLS: SkillEntry[] = [
  { name: 'architecture-depth', pct: 92 },
  { name: 'skill-match', pct: 72 },
  { name: 'type-coverage', pct: 88 },
]

export const TAB_DUR = [7000, 6000, 5000]

export const EP_LINES: EpLine[] = [
  { d: 900, c: '#7DAEEA', t: '→ C++ · Python · CMake' },
  { d: 1700, c: '#7DAEEA', t: '→ speech inference' },
  { d: 2600, c: '#6DBE8A', t: '→ 6 skills matched ✓' },
]

export const EP_CHIPS: EpChip[] = [
  { d: 800, t: 'C++', bg: 'rgba(247,246,243,.9)', bd: 'rgba(229,227,220,.9)', fg: '#0F0F0E' },
  { d: 1500, t: 'Python', bg: 'rgba(247,246,243,.9)', bd: 'rgba(229,227,220,.9)', fg: '#0F0F0E' },
  { d: 2200, t: 'CMake', bg: 'rgba(247,246,243,.9)', bd: 'rgba(229,227,220,.9)', fg: '#0F0F0E' },
  { d: 3000, t: '6 skills', bg: 'rgba(235,242,255,.9)', bd: 'rgba(195,215,247,.9)', fg: '#1A47A8' },
]

const NBSP = '\u00A0'

export const MF_LINES: MfLine[] = [
  { parts: [{ c: '#3a3a38', t: '# Generated by MARK Intelligence' }] },
  { parts: [{ c: '#ffffff', t: '# CLAUDE.md — whisper.cpp', fw: '600' }] },
  { parts: [{ c: '#3a3a38', t: NBSP }] },
  { parts: [{ c: '#E8C56A', t: '## Project Overview' }] },
  { parts: [{ c: '#E8E6E0', t: 'C++ port of OpenAI Whisper.' }] },
  { parts: [{ c: '#E8E6E0', t: 'Core: speech-to-text inference.' }] },
  { parts: [{ c: '#3a3a38', t: NBSP }] },
  { parts: [{ c: '#E8C56A', t: '## Tech Stack' }] },
  { parts: [{ c: '#7DAEEA', t: 'Language:' }, { c: '#E8E6E0', t: 'C++17, Python' }] },
  { parts: [{ c: '#7DAEEA', t: 'Build:' }, { c: '#E8E6E0', t: 'CMake 3.17+' }] },
  { parts: [{ c: '#7DAEEA', t: 'Backends:' }, { c: '#E8E6E0', t: 'Metal · CUDA · WASM' }] },
  { parts: [{ c: '#3a3a38', t: NBSP }] },
  { parts: [{ c: '#E8C56A', t: '## Selected Skills (6/59)' }] },
  { parts: [{ c: '#7DAEEA', t: 'cpp-inference, audio-processing,' }] },
  { parts: [{ c: '#7DAEEA', t: 'cross-platform-build, wasm-deploy' }] },
]

export const IDEAS: IdeaItem[] = [
  {
    name: 'SpacesTranscribe.xyz',
    tk: '$SPACES',
    desc: 'Transcribe any Twitter Space in 60s using whisper.cpp as the engine',
    est: '~4 days',
  },
  {
    name: 'VoiceMark.xyz',
    tk: '$VOICE',
    desc: 'Voice memo → CLAUDE.md context. Every Claude Code user is potential holder',
    est: '~3 days',
  },
  {
    name: 'PodcastBrief.xyz',
    tk: '$BRIEF',
    desc: 'Auto-clip alpha drops from crypto podcasts. Feed wallets, not just degens',
    est: '~5 days',
  },
]

export const TICKER_ITEMS = [
  { repo: 'vercel/next.js', ticker: '$DEPLOY' },
  { repo: 'ggerganov/whisper.cpp', ticker: '$SPACES' },
  { repo: 'supabase/supabase', ticker: '$BASE' },
  { repo: 'microsoft/vscode', ticker: '$EXT' },
  { repo: 'langchain-ai/langchain', ticker: '$CHAIN' },
]
